### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test target-redshift

on: 
  pull_request:
    types: ["opened", "synchronize", "reopened"]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1